### ISSUE TITLE
can't start Training the model

### ISSUE THREAD

**Issue by Abdelrahman-7gab** [IRIS-AUDIO/SELD#145]
Hello guys, thanks for your amazing work. 
I'm currently very interested in your model however for some reason I can't get it to start training..
so first error I received was  "Name is required" so I hardcoded the name just to get rid of that error

![image](https://user-images.githubusercontent.com/63824808/162766292-124c4edb-e427-4ac6-903d-9a0526845769.png)

so after following the readme and installing all the requirements and also changing the abspath in the 'params.py' file to 
the path containing the dataset I receive the following error:

```
Traceback (most recent call last):
  File "d:/DCASE/Code/SELD/train.py", line 394, in <module>
    main(get_param())
  File "d:/DCASE/Code/SELD/train.py", line 308, in main
    model = getattr(models, config.model)(input_shape, model_config)
  File "d:\DCASE\Code\SELD\models.py", line 24, in seldnet
    x = getattr(modules, model_config['FIRST'])(model_config['FIRST_ARGS'])(inputs)
AttributeError: module 'modules' has no attribute 'simple_conv_block'

```

after trying to trace the error. I believe that since the default params uses the 'seldnet' config file
and this config file contains "simple_conv_block" as it's "first" attribute 
however in the modules.py file there is no corresponding simple_conv_block function...

I tried to use a different model_config file with no success as well. 
(I tried the SS5.json config since there were a commit that mentioned it being the config for the DCASE submission)

![image](https://user-images.githubusercontent.com/63824808/162766985-3424a465-56c3-4587-b9bc-79f36f4cbaf4.png)

and recieved this error :

```
Traceback (most recent call last):
  File "d:/DCASE/Code/SELD/train.py", line 394, in <module>
    main(get_param())
  File "d:/DCASE/Code/SELD/train.py", line 308, in main
    model = getattr(models, config.model)(input_shape, model_config)
  File "d:\DCASE\Code\SELD\models.py", line 24, in seldnet
    x = getattr(modules, model_config['FIRST'])(model_config['FIRST_ARGS'])(inputs)
KeyError: 'FIRST'
```

I must be doing something wrong so if you can please help me start training this model that would be great 
thank you for your time and consideration.

**Comment by Abdelrahman-7gab** [comment]
check out the readme in :
https://github.com/Abdelrahman-7gab/SELD
